services:
  - type: web
    name: portfolio-optimizer-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn version2:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13
